# Generated by Django 5.0.6 on 2024-05-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_slot',
            field=models.SmallIntegerField(default=10),
        ),
    ]
