# Generated by Django 5.0.6 on 2024-05-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_booking_booking_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_slot',
            field=models.SmallIntegerField(),
        ),
    ]
